name: Draft Release

on:
  push:
    branches:
      - development

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout development branch
        uses: actions/checkout@v3
        with:
          ref: development

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install and run Release Drafter
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
